[colors]
draw_bold_text_with_bright_colors = false

### dark theme theme
[colors.bright]
black = "#595959"
blue = "#79a8ff"
cyan = "#00d3d0"
green = "#00c06f"
magenta = "#d5b1ff"
red = "#fe6060"
white = "#ffffff"
yellow = "#d0bc00"

[colors.normal]
black = "#000000"
blue = "#82b0ec"
cyan = "#00d8b4"
green = "#6ae4b9"
magenta = "#fbd6f4"
red = "#ff8059"
white = "#e0e6f0"
yellow = "#cabf77"

[colors.primary]
background = "#000000"
foreground = "#e0e6f0"

### light theme (https://github.com/rose-pine/alacritty/blob/main/dist/rose-pine-dawn.toml)
# [colors.primary]
# foreground = "#575279"
# background = "#faf4ed"
# dim_foreground = "#797593"
# bright_foreground = "#575279"

# [colors.cursor]
# text = "#575279"
# cursor = "#cecacd"

# [colors.vi_mode_cursor]
# text = "#575279"
# cursor = "#cecacd"

# [colors.search.matches]
# foreground = "#797593"
# background = "#f2e9e1"

# [colors.search.focused_match]
# foreground = "#faf4ed"
# background = "#d7827e"

# [colors.hints.start]
# foreground = "#797593"
# background = "#fffaf3"

# [colors.hints.end]
# foreground = "#9893a5"
# background = "#fffaf3"

# [colors.line_indicator]
# foreground = "None"
# background = "None"

# [colors.footer_bar]
# foreground = "#575279"
# background = "#fffaf3"

# [colors.selection]
# text = "#575279"
# background = "#dfdad9"

# [colors.normal]
# black = "#f2e9e1"
# red = "#b4637a"
# green = "#286983"
# yellow = "#ea9d34"
# blue = "#56949f"
# magenta = "#907aa9"
# cyan = "#d7827e"
# white = "#575279"

# [colors.bright]
# black = "#9893a5"
# red = "#b4637a"
# green = "#286983"
# yellow = "#ea9d34"
# blue = "#56949f"
# magenta = "#907aa9"
# cyan = "#d7827e"
# white = "#575279"

# [colors.dim]
# black = "#9893a5"
# red = "#b4637a"
# green = "#286983"
# yellow = "#ea9d34"
# blue = "#56949f"
# magenta = "#907aa9"
# cyan = "#d7827e"
# white = "#575279"

[env]
TERM = "xterm-256color"

[font.bold]
family = "Noto Sans Mono"
style = "Bold"

[font.italic]
family = "Noto Sans Mono"
style = "Italic"

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
